/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\\public\\brain_3d.glb --transform 
Files: .\\public\\brain_3d.glb [2.12MB] > E:\coding\grind_project\exovance\brain_3d-transformed.glb [290.55KB] (86%)
Author: iszz (https://sketchfab.com/iszz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/brain-3d-acc5c00c3607487d8885495b4b2258ad
Title: Brain 3D
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/brain_3d-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.material_0} />
    </group>
  )
}

useGLTF.preload('/brain_3d-transformed.glb')
