/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/3d/exovance-3d.glb --transform 
Files: ./public/3d/exovance-3d.glb [84.01KB] > E:\coding\grind_project\Exovance-company-site\exovance-3d-transformed.glb [3.77KB] (96%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/exovance-3d-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Curve003.geometry} material={materials['Material.001']} position={[0, 0.05, 0]} scale={5} />
    </group>
  )
}

useGLTF.preload('/exovance-3d-transformed.glb')
