/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\\public\\human_head.glb --transform 
Files: .\\public\\human_head.glb [1.01MB] > E:\coding\grind_project\exovance\human_head-transformed.glb [86.66KB] (91%)
Author: ADAMA (https://sketchfab.com/tnshwsh)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/human-head-41319c63c3d34f7ea6b04bf2b8c092f1
Title: Human head
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/human_head-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Scene_-_Root']} />
    </group>
  )
}

useGLTF.preload('/human_head-transformed.glb')
